import day07_laboratories as day7


EXAMPLE_INPUT = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""
EXAMPLE_RESULT = 21
EXAMPLE_RESULT_PART2 = 40


def test_splits():
    input = day7.read_input(EXAMPLE_INPUT)
    assert day7.splits(input) == EXAMPLE_RESULT


def test_timelines():
    input = day7.read_input(EXAMPLE_INPUT)
    assert day7.timelines(input) == EXAMPLE_RESULT_PART2
