import pytest
import day08_resonant_collinearity as day8


EXAMPLE_INPUT1 = """
..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
"""
EXAMPLE_RESULT1 = 2
EXAMPLE_NODES1 = {(3,1), (6,7)}

EXAMPLE_INPUT2 = """
..........
..........
..........
....a.....
........a.
.....a....
..........
......A...
..........
..........
"""
EXAMPLE_RESULT2 = 4
EXAMPLE_NODES2 = {(3,1), (6,7), (0,2), (2,6)}

EXAMPLE_INPUT3 = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
EXAMPLE_RESULT3 = 14
EXAMPLE_NODES3 = {(6,0), (11,0), (3,1), (4,2), (10,2), (2,3), (9,4),
                  (1,5), (6,5), (3,6), (0,7), (7,7), (10,10), (10,11)}
EXAMPLE_RESULT3_RES = 34


EXAMPLE_INPUT4 = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"""
EXAMPLE_RESULT4_RES = 9
EXAMPLE_NODES4_RES = {(0,0), (5,0), (3,1), (1,2), (6,2), (9,3), (2,4), (3,6), (4,8)}


def test_find_nodes1():
    antennas, gridsize = day8.read_input(EXAMPLE_INPUT1)
    assert day8.find_nodes(antennas, gridsize) == EXAMPLE_NODES1


def test_find_nodes2():
    antennas, gridsize = day8.read_input(EXAMPLE_INPUT2)
    assert day8.find_nodes(antennas, gridsize) == EXAMPLE_NODES2


def test_find_nodes3():
    antennas, gridsize = day8.read_input(EXAMPLE_INPUT3)
    assert day8.find_nodes(antennas, gridsize) == EXAMPLE_NODES3

def test_find_nodes4_res():
    antennas, gridsize = day8.read_input(EXAMPLE_INPUT4)
    print(antennas)
    assert day8.find_nodes_res(antennas, gridsize) == EXAMPLE_NODES4_RES

def test_find_nodes3_res():
    antennas, gridsize = day8.read_input(EXAMPLE_INPUT3)
    assert len(day8.find_nodes_res(antennas, gridsize)) == EXAMPLE_RESULT3_RES

